name: nubank_marketplace
description: Nubank marketplace app.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  graphql: ^5.0.0
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/logo/
    - assets/video/

  fonts:
    - family: Graphik
      fonts:
        - asset: assets/fonts/graphik/GraphikThin.otf
          weight: 100
        - asset: assets/fonts/graphik/GraphikExtralight.otf
          weight: 200
        - asset: assets/fonts/graphik/GraphikLight.otf
          weight: 300
        - asset: assets/fonts/graphik/GraphikRegular.otf
          weight: 400
        - asset: assets/fonts/graphik/GraphikMedium.otf
          weight: 500
        - asset: assets/fonts/graphik/GraphikSemibold.otf
          weight: 600
        - asset: assets/fonts/graphik/GraphikBold.otf
          weight: 700
        - asset: assets/fonts/graphik/GraphikBlack.otf
          weight: 800
        - asset: assets/fonts/graphik/GraphikSuper.otf
          weight: 900
